name: Perform Mixeway Scan

on: [push]

jobs:
  mixeway-scan:
    name: Mixeway Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Prepare variables
        id: vars
        shell: bash
	run: |
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse HEAD)"

      - name: Prepare Mixeway docker image
        run: |
          docker pull mixeway/scanner:latest

      - name: Run Scan
        run: |
          docker run \
          -e OSS_USERNAME=Neriel@interia.eu \
          -e OSS_KEY=sonatype_pat_bIcux3g-RkfABL-TRxwKGFw4y-LaaPnCnFuGC5mxxisxyu3b \
          -e MIXEWAY_URL=https://hub.mixeway.io \
          -e MIXEWAY_KEY=5ac43d17-920a-4981-92be-8f7ad559f468 \
          -e MIXEWAY_PROJECT_ID=210 \
          -e MODE=STANDALONE \
          -e MIXEWAY_PROJECT_NAME=nerie1ka_lab_secure_app \
          -e COMMIT_ID=${{ steps.vars.outputs.sha_short }} \
          -e BRANCH=${{ steps.vars.outputs.branch }} \
          -v ${{ github.workspace }}:/opt/sources \
          mixeway/scanner:latest
